apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent2
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: zabbix-agent2
  template:
    metadata:
      labels:
        app: zabbix-agent2
    spec:
      # Esto permite que el agente vea las métricas de red reales del nodo
      hostNetwork: true
      serviceAccountName: zabbix-agent2
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: zabbix-agent2
        image: {{ .Values.zabbix_agent.image }}
        env:
        - name: ZBX_SERVER_HOST
          value: {{ .Values.zabbix_agent.server_host }}
        - name: ZBX_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # Necesario para leer métricas del sistema
        securityContext:
          privileged: true
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: dev
          mountPath: /host/dev
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: rootfs
          mountPath: /host/rootfs
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: dev
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: rootfs
        hostPath:
          path: /
